title: Carlos CB
description: Hi! I’m Carlos. I’m a Data Scientist. This is my website, built to show some of my work and personal projects.
logo: /assets/img/profile_pic.jpg

markdown: kramdown

theme: jekyll-theme-minimal

author:
  name:           'Carlos CB'
  email:          'carlos.ccb.gh@gmail.com'
  url:            carlosccb.github.io
  github:         'https://github.com/carlosccb'
  linkedin:       'https://www.linkedin.com/in/carloscastillob'
  lastfm:         'https://www.last.fm/user/carloscb'
  publications:
    water_reservoir:  'https://www.mdpi.com/2073-4441/12/6/1528'
    for:              ''

encoding: utf-8
timezone: Europe/Madrid

plugins:
  - "jekyll-github-metadata"
  #- "jekyll-analytics"

# According to [https://stackoverflow.com/a/51802110] simplest way to include google analytics
google_analytics: UA-212120778-1

#jekyll_analytics:
#  GoogleAnalytics:         # Add, if you want to track with Google Analytics
#    id: G-FS1NNLXRF4       # Required - replace with your tracking id
#    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking
